//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GymWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGymProfile
    {
        public string GymProfileId { get; set; }
        public string FName { get; set; }
        public string LName { get; set; }
        public string GymName { get; set; }
        public string EMailId { get; set; }
        public string GymMemberShipId { get; set; }
        public string MemberShipStatus { get; set; }
        public string MobileNumber { get; set; }
        public string Website { get; set; }
        public string Address { get; set; }
        public string GSTNo { get; set; }
        public string LastUpdatedBy { get; set; }
        public System.DateTime LastUpdatedDt { get; set; }
    }
}
