//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GymWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGymMbr
    {
        public string MbrId { get; set; }
        public string MbrName { get; set; }
        public string MbrType { get; set; }
        public string MbrMob { get; set; }
        public string MbrDOB { get; set; }
        public string MbrMarrialStatus { get; set; }
        public string MbrDOE { get; set; }
        public string MbrEmail { get; set; }
        public string MbrAddr { get; set; }
        public string MbrCity { get; set; }
        public string MbrState { get; set; }
        public string MbrPincode { get; set; }
        public string MbrShipId { get; set; }
        public string SalId { get; set; }
        public string LastUpdatedBy { get; set; }
        public string LastUpdatedDt { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public string MbrMob2 { get; set; }
        public Nullable<int> MbrPTCharges { get; set; }
        public string MbrBatch { get; set; }
        public string GeneralDesc { get; set; }
        public string MbrGender { get; set; }
    }
}
