//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GymWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGymExpens
    {
        public string ExpensesId { get; set; }
        public int Amount { get; set; }
        public string Category { get; set; }
        public string Description { get; set; }
        public string ExpenseDate { get; set; }
        public string LastUpdatedBy { get; set; }
        public string SubCategory { get; set; }
        public System.DateTime LastUpdatedDt { get; set; }
    }
}
