//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GymWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMbrShipPlan
    {
        public string MbrShipId { get; set; }
        public string MbrShipName { get; set; }
        public int MbrShipAmt { get; set; }
        public int MbrShipDurationInDays { get; set; }
        public bool Active { get; set; }
        public string LastUpdatedDt { get; set; }
        public string StartDt { get; set; }
        public string EndDt { get; set; }
        public string Description { get; set; }
        public string LastUpdatedBy { get; set; }
        public string PlanType { get; set; }
    }
}
