//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GymWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMbrShipPlanUser
    {
        public string MbrUserId { get; set; }
        public string MbrShipId { get; set; }
        public string MbrId { get; set; }
        public Nullable<int> PaidAmt { get; set; }
        public string PaidBy { get; set; }
        public string CardNumber { get; set; }
        public int Disscount { get; set; }
        public string PaidDt { get; set; }
        public string Discription { get; set; }
        public string MbrshipStartDt { get; set; }
        public string MbrshipEndDt { get; set; }
        public string MembershipType { get; set; }
        public string sessionTime { get; set; }
        public Nullable<int> RemBalance { get; set; }
        public string TrainerId { get; set; }
        public Nullable<bool> IsRenewed { get; set; }
        public System.DateTime LastUpdatedDt { get; set; }
        public string LastUpdatedBy { get; set; }
    }
}
