//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GymWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Template
    {
        public string Id { get; set; }
        public string TemplateType { get; set; }
        public string TemplateKey { get; set; }
        public string Template1 { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime AddedDate { get; set; }
    }
}
